services:
  backend:
    build:
      context: table2taste-backend_springboot
      dockerfile: Dockerfile
    volumes:
      - ./table2taste-backend_springboot:/app:cached
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: table2taste-frontend
      dockerfile: Dockerfile
    volumes:
      - ./table2taste-frontend:/app:cached
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped

  db:
    build:
      context: table2taste-db
      dockerfile: Dockerfile
    volumes:
      - ./table2taste-db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped