version: '3.8'

services:
  backend:
    build:
      context: table2taste-backend
      dockerfile: Dockerfile
    volumes:
      - ./table2taste-backend:/app:cached
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: sleep infinity

  frontend:
    build:
      context: table2taste-frontend
      dockerfile: Dockerfile
    volumes:
      - ./table2taste-frontend:/app:cached
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    command: sleep infinity

  db:
    build:
      context: table2taste-db
      dockerfile: Dockerfile
    volumes:
      - ./table2taste-db/data:/var/lib/postgresql/data
      - ./table2taste-db/db-init-scripts:/docker-entrypoint-initdb.d:cached
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
