apiVersion: v1
kind: Secret
metadata:
  name: table2taste-secrets
  namespace: table2taste
type: Opaque
stringData:
  POSTGRES_USER: "table-2-taste"
  POSTGRES_PASSWORD: "SCbK9nkVHcgjLS"
  JWT_SECRET: "5ee9b307d37af03d6081d53f0ab8756b9d38b00f61a125525531e1b436b0f66d"
  TABLE_PASSWORD: "xgEne4Kq"
